export const TYPE_RU={normal:'Обычный',fire:'Огненный',water:'Водный',electric:'Электрический',grass:'Травяной',ice:'Ледяной',fighting:'Боевой',poison:'Ядовитый',ground:'Земляной',flying:'Летающий',psychic:'Психический',bug:'Насекомый',rock:'Каменный',ghost:'Призрачный',dragon:'Драконий',dark:'Тёмный',steel:'Стальной',fairy:'Волшебный'};
export const STAT_RU={hp:'Здоровье',attack:'Атака',defense:'Защита',specialAttack:'Спец. атака',specialDefense:'Спец. защита',speed:'Скорость'};
export function normalize(s){return String(s??'').toLowerCase().trim().replaceAll('ё','е');}
export function filterPokemon(list,{q='',type='all',generation='all',sort='id'}={}){const term=normalize(q).replace(/^#0*/,'');const result=list.filter(p=>(!term||normalize(p.name).includes(term)||normalize(p.nameRu).includes(term)||String(p.id)===term)&&(type==='all'||p.types.includes(type))&&(generation==='all'||String(p.generation)===String(generation)));return result.sort((a,b)=>sort==='name'?a.nameRu.localeCompare(b.nameRu,'ru'):sort==='speed'?b.stats.speed-a.stats.speed||a.id-b.id:sort==='total'?statTotal(b)-statTotal(a)||a.id-b.id:a.id-b.id);}
export function statTotal(p){return Object.values(p.stats).reduce((a,b)=>a+b,0);}
export function multiplier(attack,defenders,chart){return defenders.reduce((value,type)=>value*(chart[attack]?.[type]??1),1);}
export function sanitizeTeam(ids,list){if(!Array.isArray(ids))return [];const known=new Set(list.map(p=>p.id));return [...new Set(ids.filter(id=>typeof id==='number'||(typeof id==='string'&&/^\d+$/.test(id))).map(Number).filter(id=>Number.isInteger(id)&&known.has(id)))].slice(0,6);}
export function addMember(team,id,list){const clean=sanitizeTeam(team,list);if(!(typeof id==='number'||(typeof id==='string'&&/^\d+$/.test(id))))return {team:clean,status:'invalid'};id=Number(id);if(clean.includes(id))return {team:clean,status:'duplicate'};if(clean.length>=6)return {team:clean,status:'full'};if(!list.some(p=>p.id===id))return {team:clean,status:'invalid'};return {team:[...clean,id],status:'added'};}
export function analyzeTeam(ids,list,chart){const team=sanitizeTeam(ids,list).map(id=>list.find(p=>p.id===id));return Object.keys(TYPE_RU).map(type=>{const values=team.map(p=>multiplier(type,p.types,chart));return {type,weak:values.filter(v=>v>1).length,strong:values.filter(v=>v<1).length,immune:values.filter(v=>v===0).length,neutral:values.filter(v=>v===1).length,max:values.length?Math.max(...values):0,stab:team.filter(p=>p.types.some(a=>multiplier(a,[type],chart)>1)).length};});}
export function parseFilters(search){const p=new URLSearchParams(search);return {q:p.get('q')??'',type:Object.hasOwn(TYPE_RU,p.get('type'))?p.get('type'):'all',generation:['1','2','3','4','5','6','7','8','9'].includes(p.get('generation'))?p.get('generation'):'all',sort:['id','name','speed','total'].includes(p.get('sort'))?p.get('sort'):'id'};}
export function filtersQuery(state){const p=new URLSearchParams();for(const [key,val] of Object.entries(state))if(val&&val!=='all'&&!(key==='sort'&&val==='id'))p.set(key,val);return p.toString();}
export function parseStored(text,fallback){try{return JSON.parse(text)??fallback;}catch{return fallback;}}
export function expeditionSuggestion(mode,list){const candidates={water:[658,350,134],mountain:[445,448,715],forest:[1,196,470]};return (candidates[mode]??candidates.water).filter(id=>list.some(p=>p.id===id));}
export function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
// Named defensive outcomes, separate from the original count-only public API.
export function defenseMembers(ids,list,chart,type){return sanitizeTeam(ids,list).map(id=>{const p=list.find(p=>p.id===id);return {id,name:p.name,nameRu:p.nameRu,multiplier:multiplier(type,p.types,chart)};});}
